apiVersion: v1
kind: Service
metadata:
  name: advertiseproject-rpc-nodeport
  labels:
    app: advertiseproject
spec:
  selector:
    app: advertiseproject
  ports:
    - name: rpc
      port: 8888
      targetPort: 8888
      nodePort: 30088
      protocol: TCP
  type: NodePort
