apiVersion: v1
kind: Service
metadata:
  name: advertiseproject-rpc
  labels:
    app: advertiseproject
spec:
  selector:
    app: advertiseproject
  ports:
    - name: rpc
      port: 8888
      targetPort: 8888
      protocol: TCP
  type: ClusterIP
